CREATE TABLE article (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
    REF VARCHAR(30),
	DESIGNATION VARCHAR(255),
	PRIX DECIMAL(7,2),
	ID_FOU INT(11));
    
CREATE TABLE fournisseur (
	ID INT(11) AUTO_INCREMENT PRIMARY KEY,
	NOM VARCHAR(255));
    
CREATE TABLE bon (
    ID INT(11) AUTO_INCREMENT PRIMARY KEY,
	NUMERO INT(11),
	DATE_CMDE DATETIME,
	DELAI INT(11),
	ID_FOU INT(11));
    
CREATE TABLE compo (
	ID INT(11) AUTO_INCREMENT PRIMARY KEY,
	ID_ART INT(11),
	ID_BON INT(11),
	QTE INT(11));
    
ALTER TABLE article ADD CONSTRAINT FOREIGN KEY (ID_FOU) REFERENCES fournisseur(ID);
ALTER TABLE bon ADD CONSTRAINT FOREIGN KEY (ID_FOU) REFERENCES fournisseur(ID);
ALTER TABLE compo ADD CONSTRAINT FOREIGN KEY (ID_ART) REFERENCES article(ID);
ALTER TABLE compo ADD CONSTRAINT FOREIGN KEY (ID_BON) REFERENCES bon(ID);